### ISSUE TITLE
Improve install times

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#262]
Currently even for a small cluster (3 etcd, 2 masters and 2 workers) the install time is about 15 minutes.
There are 2 plays that take up a significant portion of the install time:
* `Install Kismatic packages`
* `Install Docker -> load local docker images` 

Both of these are caused by the same underlying factor: the inclusion of docker images in our kismatic packages.

The contents of the k8s packages: `images` contain the docker images and are about 60% of the total size.
```
 27M	docker
 53M	etcd
905M	images
459M	kubernetes
 85M	networking
```

By including the images in the packages:
1. Those images are downloaded from a slow S3 source to each node
2. Cannot take advantage of docker caching and layers

The initial reasoning for this technique was to support offline installs. We can improve the performance by treating `offline` as an optional feature with a separate k8s package containing all the bits needed to support that offline workflow. 

**TODO:**
- [x] Create new package with the needed bits (docker images)
- [x] Modify `kismatic` CLI for standard/online flow
        * Don't load docker images from a local dir
        * Method to determine if the install is online or offline -> this will drive the url for the docker images used during the install: new plan file variable
- [x] Modify `kismatic` CLI for offline flow
        * Install new package
        * Load docker images in the local docker registry
        * Use the local docker registry url
- [x] Modify `kuberang` to accept an optional parameter `--docker-registry-url`
